// +build !ignore_autogenerated

// My header

// Code generated by helpgen. DO NOT EDIT.

package main

import (
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func (Generator) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "",
		DetailedHelp: markers.DetailedHelp{
			Summary: "generates code containing ShallowCopy method implementations.",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{},
	}
}
